name: Build Skia + QuestPDF

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.runtime.name }}
    runs-on: ${{ matrix.runtime.runs-on }}
    container: ${{ matrix.runtime.container }}
      
    strategy:
      fail-fast: false
      matrix:
        runtime: 
        - name: win-x64
          runs-on: windows-latest-large
        - name: win-x86
          runs-on: windows-latest-large
        - name: linux-x64
          runs-on: ubuntu-latest-large
          container: ubuntu:18.04
        - name: linux-arm64
          runs-on: [self-hosted, linux, arm64]
          container: ubuntu:18.04
        - name: linux-musl-x64
          runs-on: ubuntu-latest-large
          container: alpine:3.17
        - name: osx-x64
          runs-on: macos-latest-large
        - name: osx-arm64
          runs-on: macos-latest-large

    steps:
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

          
      - name: Test build artifacts
        shell: bash
        run: |
          dotnet --info
